### ISSUE TITLE
`do` command doesn't supply `from` spender address

### ISSUE THREAD

**Issue by cryptogoth** [invisible-college/democracy#9]
The new command for interacting with smart contract methods doesn't supply the `from` field
```
[root@c9d5ebcafd2f democracy]# ./demo.js do TestUseLibrary test deployE double _def=2
Command do
arg TestUseLibrary
  <0 ContractName>=TestUseLibrary, <1 netName>=test, <2 deployId>=deployE, <3 methodName>=double, <4 args>=_def=2
Network test
Coinbase: [object Object]
Net: test
Doing TestUseLibrary.double with args [object Object]
Args '2'
(node:16242) UnhandledPromiseRejectionWarning: Error: [ethjs-query] while formatting inputs '[{"to":"0x2250c7f93e7d1644b5a10029e35144a74b900e99","data":"0xeee9720600000000000000000000000000000000000
00000000000000000000000000002"}]' for method 'sendTransaction' error: Error: [ethjs-format] object {"to":"0x2250c7f93e7d1644b5a10029e35144a74b900e99","data":"0xeee97206000000000000000000000000000000
0000000000000000000000000000000002"} must contain properties: from, data
    at Eth._callee$ (/src/democracy/node_modules/ethjs-query/lib/index.js:110:23)
    at tryCatch (/src/democracy/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/src/democracy/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/src/democracy/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/src/democracy/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /src/democracy/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/src/democracy/node_modules/core-js/library/modules/_export.js:36:28)
    at Eth.<anonymous> (/src/democracy/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at Eth.performCall (/src/democracy/node_modules/ethjs-query/lib/index.js:141:21)
```

To reproduce
 446  ./demo.js link TestUseLibrary test account0 link2 TestLibrary=deploy7
  447  git status
  448  vi src/TestUseLibrary.sol
  449  ./demo.js compile TestUseLibrary.sol
  450  ./demo.js link TestUseLibrary test account0 link2 TestLibrary=deploy7
  451  ./demo.js link TestUseLibrary test account0 link2 TestLibrary=deploy7
  452  ./demo.js link TestUseLibrary test account0 link3 TestLibrary=deploy7
  453  ./demo.js deploy TestUseLibrary test link2 deployD _abc=123
  454  ./demo.js deploy TestUseLibrary test link2 deployE _abc=123
  455  ./demo do
  456  ./demo.js do
  457  ./demo.js info TestUseLibrary
  458  ./demo do
  459  ./demo.js do TestUseLibrary
  460  ./demo.js do TestUseLibrary test deployE double _def=2

**Comment by cryptogoth** [comment]
the design of a `do` command requires more thought, not least of which that `do` is a reserved keyword in Javascript.
